form/urls.py
from django.conf.urls import url
from django.urls import path
from .views import homes, validate_mail, renders, tampil, jsonreq, remove
app_name= 'form'
urlpatterns = [
    url(r'^$', renders, name='render'),
    url(r'^submit', homes, name='home'),
    url(r'^validate-mail', validate_mail, name='validate-mail'),
    url(r'^list', tampil, name='tampil'),
    url(r'^data', jsonreq, name='data'),
    url(r'^remove', remove, name='remove'),
   
]

ppwbaru/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path,include
from story.views import hello
from django.views.generic import RedirectView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('subscribe/', include('form.urls', namespace="form")),
    path('', include('story.urls', namespace="story")),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
    
]

story/urls.py
from django.conf.urls import url
from django.urls import path
from .views import hello, home, library, jsonreq, login, logout_view
app_name= 'story'
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^form', hello, name='hello'),
    url(r'^library', library, name='library'),
    url(r'^logout', logout_view, name='logout'),
    url(r'^login', login, name='login'),
    path('data/<pilih>', jsonreq),
]

form/models.py
from django.db import models

# Create your models here.
class Subs(models.Model):
    fullname = models.CharField(max_length=60)
    email = models.EmailField(max_length=30, unique=True)
    password = models.CharField(max_length=30)

story/models.py
from django.db import models
from datetime import datetime

class Orang(models.Model):
    isi = models.CharField(max_length=300)
    date= models.DateTimeField(auto_now_add=True)

# Create your models here.

form/forms.py
from django import forms
from .models import Subs

class SubsForm(forms.Form):
    fullname = forms.CharField(label = "Name", required = True, max_length=60, widget=forms.TextInput())
    email = forms.EmailField(label= "Email", required = True, max_length=30)
    password = forms.CharField(label = "Password", max_length=30, required=True,widget=forms.PasswordInput())
    

story/forms.py
from django import forms
from .models import Orang
class Forms(forms.Form):
    attrs= {Orang:Orang}
    isi = forms.CharField(label='input:', required=True, max_length=300,widget=forms.TextInput(attrs=attrs))
    
    

form/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError
from django.http import HttpResponse
from .models import Subs
from .forms import SubsForm
from django.http import JsonResponse
from django.db import IntegrityError
import json
import requests 

# Create your views here.
response = {}

def renders(request):
    form = SubsForm(request.POST or None)
    response['form'] = form
    return render(request, 'subs.html', response)

    
def homes(request):
    try:
        if(request.method == "POST"):
            fullname = request.POST.get('fullname', None)
            email = request.POST.get('email', None)
            password = request.POST.get('password', None)
            Subs.objects.create(fullname=fullname, email=email,password=password)
            return HttpResponse(json.dumps({'result': 'success, thank you ' + fullname,
                                            'email': email,
                                            'name': fullname
                                            }))
        else:
            return HttpResponse(json.dumps({'result': 'fail'}))

    except IntegrityError as e:
        return HttpResponse(json.dumps({'result': 'fail'}))


def validate_mail(request):
    mail = request.POST.get('email', None)
    data = {
        'is_taken': Subs.objects.filter(email=mail).exists()
    }
    return JsonResponse(data)

def tampil(request):
    response['isi']= Subs.objects.all()
    return render (request,'list.html', response)

def jsonreq(request):
    sub= Subs.objects.all()
    lists= list()
    for i in sub:
        orang={ 'nama': i.fullname, 'email': i.email}
        lists.append(orang)
    return HttpResponse(json.dumps({'items': lists}))

def remove(request):
    email = request.POST.get('email', None)
    Subs.objects.all().filter(email=email).delete()
    return HttpResponse(json.dumps({'items': email}))

story/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from .forms import Forms
from .models import Orang
from datetime import datetime
from django.http import HttpResponse
import requests 
import json
from django.http import JsonResponse
from django.contrib.sessions.backends.db import SessionStore
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
# Create your views here.
response={}

def hello(request):
    form= Forms(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        isi = request.POST['isi']
        date= datetime.now()
        isian= Orang(isi=isi, date=date)
        isian.save()
        message = Orang.objects.all()
        response['message'] = message
        return render(request, "hello.html", response)
    else:
        response['form']= Forms
        message = Orang.objects.all()
        response['message'] = message
        return render(request, "hello.html", response)

def home(request):
        return render(request, "Home.html")


def library(request):
    if request.user.is_authenticated:
        user=User.objects.get(email=request.user.email)
        social = user.social_auth.get(uid=request.user.email)
        request.session['name']= request.user.first_name
        request.session['token']= social.extra_data['access_token']
        request.session['email']= request.user.email
    else:
        request.session['name']= "My"
    response['name']= request.session['name']
    print(request.session['name'])
    return render(request, "library.html", response)

def logout_view(request):
    logout(request)
    request.session.flush()
    return redirect('story:library')
def login(request):
    return redirect('story:library')


##@csrf_exempt
##def update(request):
##    nama = request.POST.get('name', None)
##    request.session['name']= nama
##    request.session.save()
##    return render(request, "library.html", response)


def jsonreq(request, pilih=None):
    url = requests.get("https://www.googleapis.com/books/v1/volumes?q="+ str(pilih))
    jsons= url.json()
    return JsonResponse(jsons)

form/templates/list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<head>
{% csrf_token %}
<script src="{% static 'js/form.js' %}"></script>
<link rel="stylesheet" type="text/css" href='/static/css/style.css'>
</head>


<div  style="display:none;" id='isi'>
	<center>
	<table id= 'data' class="table table-responsive container" style="text-align: center; background-color:rgb(255,255,255,0.5)">
			<tr>
                <th id='table'>Name</th>
                <th id='table'>E-mail</th>
				<th> Unsubscribe </th>
            </tr>
</table>
	
	</center>
</div>


{% endblock %}

form/templates/subs.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<head>
{% csrf_token %}
<script src="{% static 'js/form.js' %}"></script>
<link rel="stylesheet" type="text/css" href='/static/css/style.css'>
</head>


<div  style="display:none;" id='isi'>
	<center>
	<div class="container">
            <h1 style='margin-top:25px;margin-bottom:50px;'>Keep you updated</h1>
            <form  method="POST">
            {% csrf_token %}
            {% for field in form %}
                <p class="label_tag">{{ field.label_tag }} <br> {{ field }} </p> 
            {% endfor %}
            <input style="margin-bottom:10px" disabled=true class="btn btn-info btn-lg" id="submit"  type="submit" value="Submit" >
         </form>
    </div>
	<div id="dialog" title="Announcement">
	</div>
	<div id='peringatan' style="margin-bottom:30vh">
	
	</div>
	<a href="{% url 'form:tampil' %}"><button class="btn btn-info"  >List Of Subscriber</button></a>
	</center>
</div>


{% endblock %}

story/templates/Home.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div  style="display:none;" id='isi'>
	<center>
	<h1> HELLO. </h1>
	<img  src="https://preview.ibb.co/gw0P0K/IMG_20180630_152039_2.jpg" alt="IMG_20180630_152039" align="middle"  width="200" height="200" style="border-radius:180px; margin-top:10px; margin-bottom:10px">
	<h2>Nama saya</h2>
	<h2><strong>Ali Yusuf</strong></h2>
	
	<div id="accordion" style="width: 300px">
		<h3>My Activities</h3>
		<div>
			Kuliah<br>Tidur<br>Makan
		</div>
		<h3>Experience</h3>
		<div>
			OH FASILKOM 2018<br>SIWAK-NG 2018<br>DPM FASILKOM 2018
		</div>
		<h3>Achievement</h3>
		<div>
			Juara 1 Turnamen RW<br>Juara 2 Turnamen Lurah
		</div>
	</div>
	<br>
   <button class="btn btn-info" id='button' >Change theme</button>
	<h3>Anak UI</h1>
	
	
</center>
</div>
{% endblock %}

story/templates/hello.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div  style="display:none;" id='isi'>
<center>
<h1>Hello, apa kabar</h1>
<form class="Box" method="POST" action="{% url 'story:hello' %}" > 
{% csrf_token %} 
{{ form }} 
<br> <br>
<button type="submit" class="btn btn-default">Submit</button> 
</form>
<br>
<table align="center" style="text-align: center;  padding:100px">
			<tr>
                <th id='table'>Status</th>
                <th id='table'>Date</th>
            </tr>

{% for diary_data in message %}
			
			
                <tr >
					<td id='table' class="activity">{{ diary_data.isi }}</td>
					<td id='table' class="type_act">{{ diary_data.date }}</td> 
                </tr>
            {% endfor %}
</table>
<br> 
</center>
</div>
{% endblock %}

story/templates/library.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div  style="display:none " id='isi' class='images' >
<center>
<!-- <div class="g-signin2" onclick='reload()' data-onsuccess="onSignIn"></div>
<a href="#" onclick="signOut();">Sign out</a>
<script>
  function reload() {
	location.reload();
  }
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
	  sessionStorage.clear();
	  sessionStorage.setItem("name","My");
	  $.ajax({
		url: '/update' ,
		method: "POST",
		
		data: {
            'name': "My", 
        },
		success: function(data) {
                    location.reload();
					}
		})
		event.preventDefault();
    });
  }
</script> -->
{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
			 
	{% else %}
	<div class="google" style="margin-bottom:20px">
     <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
         <div class="left">
             <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
         </div>
         Login with Google
     </a>
	</div>       

{% endif %}

<h3>Total of {{name}} Favorite Books: </h3>
<div id="favi" style='margin-top:20px'>
</div>
<div>
<h4>Categories:</h4>
<button class="btn btn-info" onclick='pilih("Architecture")' >Architecture</button>
<button class="btn btn-info" onclick='pilih("Comic")' >Comic</button>
<button class="btn btn-info" onclick='pilih("Quilting")' >Quilting</button>
<button class="btn btn-info" onclick='pilih("Django")' >Django</button>
</div>
<table id= 'datas' class="table table-responsive container" style="text-align: center; background-color:rgb(255,255,255,0.5)">
			<tr>
                <th id='table'>Cover</th>
                <th id='table'>Title</th>
				<th id='table'>Author</th>
				<th> Fav </th>
            </tr>
</table>
{% if user.is_authenticated %}
        <a href="{% url 'story:logout' %}" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-log-out"></span> Log out
        </a>
      

{% endif %}      

</center>
</div>
 {% endblock %}

story/templates/login.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div  style="display:none;" id='isi'>
	<center>
	<h2>Login</h2>
	<a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
	</center>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ali</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="google-signin-client_id" content="258812013582-re36741546pe4ogek7mjbk6m2k5e5ne6.apps.googleusercontent.com">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
	<script src="{% static 'js/jquery-ui.js' %}"></script>
	<script src="{% static 'js/style.js' %}"></script>
	<script src="https://apis.google.com/js/platform.js" async defer></script>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type='text/css' href='/static/css/jquery-ui.css'>
	<link rel="stylesheet" type="text/css" href='/static/css/tes.css'>
	<link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Short+Stack" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<nav class="navbar navbar-expand-lg  navbar-light"  id="navbar" >
	<a class="navbar-brand" href="{% url 'story:home' %}">
	<img src="https://image.flaticon.com/icons/svg/25/25694.svg" width="30" height="30" alt="">
	</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0 navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story:home' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story:hello' %}">Form</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="{% url 'story:library' %}">Library</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="{% url 'form:render' %}">Follow Me</a>
      </li>
    </ul>
  </div>
</nav>
<body onload=setTimeout("showPage()",2000) >

<div id="loader" >
	<center>
	<br><br><br><img src='http://bsn.ie/wp-content/uploads/2018/06/QuarterlyThirdBlacklab.gif' style="width:350px"><br><br><br><br><br><br><br><br><br><br>
	</center>
</div>
        {% block content %}
        {% endblock %}

</body>
</html>